name: cgr_bench
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - joblib
  - pytorch
  - pip
  - pip:
      - transformers>=4.45
